logging:
  level:
    org.springframework.cloud.gateway: DEBUG
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"
management:
  endpoint:
    #    health:
    #      show-details: when_authorized
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "gateway"
  server:
    port: 8080
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test
#          uri: "http://httpbin.org"
#          predicates:
#            - Path=/test/**
#          filters:
#            - StripPrefix=1
